### ISSUE TITLE
Implementation details about BD-PnP.

### ISSUE THREAD

**Issue by JiChun-Wang** [princeton-vl/Coupled-Iterative-Refinement#1]
Thanks for your provided code.
I don't understand why you used Ji when computing the Jacobian matrix about G0 as follows:
https://github.com/princeton-vl/Coupled-Iterative-Refinement/blob/fa7eed5cc1728705bf373c5b65283284b5d6f859/utils/geom/projective_ops_rgbd.py#L91
I'm new to Lie group theory, and as far as my knowledge is concerned, Jj seems to be the Jacobian needed.
Hope for your help.

**Comment by lahavlipson** [comment]
This is true when Jj corresponds to the pose of the object in the image, rather than a rendered view. However, we also compute flow in the opposite direction, in which case Ji corresponds to the pose of the object in the image.  The Js corresponding to the rendered views all get discarded [here](https://github.com/princeton-vl/Coupled-Iterative-Refinement/blob/fa7eed5cc1728705bf373c5b65283284b5d6f859/utils/geom/ba.py#L200) just before solving for the update.

**Comment by lahavlipson** [comment]
I am closing this issue. Feel free to re-open.
