### ISSUE TITLE
Poses in the world coordinates

### ISSUE THREAD

**Issue by shanice-l** [princeton-vl/Coupled-Iterative-Refinement#3]
Hi authors!

Thanks for your great work! 
I've noticed that you used the object poses in the world coordinates. Could you please tell me your consideration? Can I replace it with object poses in camera coordinates?

RSVP.

**Comment by lahavlipson** [comment]
Yes, you can use object poses in camera coordinates instead of world coordinates. Please note that you will have to swap variables `ii` and `jj` in the input to `projective_transform`, `MoBA` and `BA` accordingly. If you're using the Modified BD-PnP approach, you'll also need to invert the pose input to `renderer `.

We use world coordinates since this is the format expected by the BOP benchmark.

**Comment by shanice-l** [comment]
Oops, I understood it. You wrote P = K^(-1)KP in your code, and it's a little bit confusing.
